set_property board_part em.avnet.com:microzed_7020:part0:1.1 [current_project]

upgrade_ip [get_ips  system_processing_system7_0_0] -log ip_upgrade.log

export_ip_user_files -of_objects [get_ips ] -no_script -sync -force -quiet
generate_target all [get_files  *.bd]

create_ip_run [get_files -of_objects [get_fileset sources_1] *.bd]

set_property -dict [list CONFIG.PCW_DDR_RAM_HIGHADDR {0x3FFFFFFF}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_ENET0_GRP_MDIO_IO {EMIO}] [get_bd_cells processing_system7_0]


set_property -dict [list CONFIG.PCW_MIO_TREE_PERIPHERALS "unassigned#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#Enet 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#USB 0#SD 0#SD 0#SD 0#SD 0#SD 0#SD 0#SD 0#unassigned#UART 1#UART 1#SD 0#unassigned#unassigned#unassigned"] [get_bd_cells processing_system7_0]

set_property -dict [list CONFIG.PCW_MIO_TREE_SIGNALS "unassigned#qspi0_ss_b#qspi0_io[0]#qspi0_io[1]#qspi0_io[2]#qspi0_io[3]/HOLD_B#qspi0_sclk#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#tx_clk#txd[0]#txd[1]#txd[2]#txd[3]#tx_ctl#rx_clk#rxd[0]#rxd[1]#rxd[2]#rxd[3]#rx_ctl#data[4]#dir#stp#nxt#data[0]#data[1]#data[2]#data[3]#clk#data[5]#data[6]#data[7]#clk#cmd#data[0]#data[1]#data[2]#data[3]#cd#unassigned#tx#rx#wp#unassigned#unassigned#unassigned"] [get_bd_cells processing_system7_0]

set_property -dict [list CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY0 {0.371}] [get_bd_cells processing_system7_0] 
set_property -dict [list CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY1 {0.363}] [get_bd_cells processing_system7_0] 
set_property -dict [list CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY2 {0.414}] [get_bd_cells processing_system7_0] 
set_property -dict [list CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY3 {0.416}] [get_bd_cells processing_system7_0] 
set_property -dict [list CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_0 {-0.090}] [get_bd_cells processing_system7_0] 
set_property -dict [list CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_1 {-0.054}] [get_bd_cells processing_system7_0] 
set_property -dict [list CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_2 {0.017}] [get_bd_cells processing_system7_0] 
set_property -dict [list CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_3 {-0.007}] [get_bd_cells processing_system7_0] 
set_property -dict [list CONFIG.PCW_PACKAGE_NAME {clg400}] [get_bd_cells processing_system7_0] 

set_property -dict [list CONFIG.PCW_SD0_GRP_WP_IO {MIO 50}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_SD0_GRP_CD_IO {MIO 46}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY0 {0.296}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY1 {0.3}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY2 {0.343}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY3 {0.338}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_CLOCK_0_LENGTH_MM {39.7}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_CLOCK_0_PACKAGE_LENGTH {80.4535}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_CLOCK_1_LENGTH_MM {39.7}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_CLOCK_1_PACKAGE_LENGTH {80.4535}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_CLOCK_2_LENGTH_MM {54.14}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_CLOCK_2_PACKAGE_LENGTH {80.4535}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_CLOCK_3_LENGTH_MM {54.14}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_CLOCK_3_PACKAGE_LENGTH {80.4535}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DEVICE_CAPACITY {4096 MBits}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DQS_0_LENGTH_MM {50.05}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DQS_0_PACKAGE_LENGTH {105.056}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DQS_1_LENGTH_MM {50.43}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DQS_1_PACKAGE_LENGTH {66.904}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DQS_2_LENGTH_MM {50.10}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DQS_2_PACKAGE_LENGTH {89.1715}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DQS_3_LENGTH_MM {50.01}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DQS_3_PACKAGE_LENGTH {113.63}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_0 {-0.069}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_1 {-0.065}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_2 {0.024}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_3 {0.021}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DQ_0_LENGTH_MM {49.59}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DQ_0_PACKAGE_LENGTH {98.503}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DQ_1_LENGTH_MM {51.74}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DQ_1_PACKAGE_LENGTH {68.5855}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DQ_2_LENGTH_MM {50.32}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DQ_2_PACKAGE_LENGTH {90.295}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DQ_3_LENGTH_MM {48.55}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_DQ_3_PACKAGE_LENGTH {103.977}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_FREQ_MHZ {533.333333}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_PARTNO {MT41K256M16 RE-125}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_ROW_ADDR_COUNT {15}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_T_FAW {40.0}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_T_RAS_MIN {35.0}] [get_bd_cells processing_system7_0]
set_property -dict [list CONFIG.PCW_UIPARAM_DDR_T_RC {48.75}] [get_bd_cells processing_system7_0]

